#application.yml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.224.113/mybatis
    username: root
    password: ZW042104wz

mybatis:
  type-aliases-package: com.example.springbootquickstart.pojo
  mapper-locations: classpath:/mapper/**/*.xml

